name: Pulumi
on:
  push:
    branches:
      - pulumi
jobs:
  up:
    name: Update
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: 'eu-north-1'
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install
        run: npm install
      - name: Production build
        run: npm run build
      - name: Run tests
        run: npm test

      - name: Run Pulumi
        uses: pulumi/actions@v3
        with:
          working-directory: ./pulumi
          command: up
          stack-name: dev
          # cloud-url: s3://my-bucket-name
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # AWS_REGION: 'eu-north-1'
